---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/mattsqwj/public_html
      - export DEPLOYPATH=/home/mattsqwj/mattdoering.pizza
      - /bin/cp index.html $DEPLOYPATH
      - /bin/cp -R assets $DEPLOYPATH
      - /bin/cp -R images $DEPLOYPATH
      - /bin/cp matts_resume_2021.pdf $DEPLOYPATH
